# Generated by Django 3.2.5 on 2021-10-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLAN_DATE', models.CharField(max_length=15)),
                ('DP_MNYR', models.CharField(max_length=6)),
                ('SBU_ID', models.CharField(max_length=10)),
                ('SALES_AREA_ID', models.CharField(max_length=10)),
                ('SORT_ORDER', models.CharField(max_length=10)),
                ('STATUS', models.CharField(max_length=10)),
                ('CREATED_BY', models.CharField(max_length=10)),
                ('CREATED_AT', models.CharField(max_length=15)),
                ('UPDATED_BY', models.CharField(max_length=10)),
                ('UPDATED_AT', models.CharField(max_length=15)),
            ],
        ),
    ]
