# Generated by Django 3.2.5 on 2021-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SD_DELIVERY_PLAN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryplan',
            name='CREATED_AT',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='deliveryplan',
            name='UPDATED_AT',
            field=models.CharField(max_length=25),
        ),
    ]
