# Generated by Django 3.2.5 on 2021-10-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SD_DELIVERY_PLAN', '0002_auto_20211011_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryplan',
            name='SORT_ORDER',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryplan',
            name='UPDATED_BY',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
